# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  telemetry:
    logging:
      console:
        _type: console
        level: WARN
      file:
        _type: file
        path: ./.tmp/email_phishing_analyzer.log
        level: DEBUG

functions:
  email_phishing_analyzer:
    _type: email_phishing_analyzer
    llm: phishing_llm
    optimizable_params:
      - prompt
  prompt_init:
    _type: prompt_init
    optimizer_llm: prompt_optimizer
    system_objective: Agent that triages an email to see if it is a phishing attempt or not.
  prompt_recombination:
    _type: prompt_recombiner
    optimizer_llm: prompt_optimizer
    system_objective: Agent that triages an email to see if it is a phishing attempt or not.

llms:
  phishing_llm:
    _type: nim
    model_name: meta/llama-3.1-405b-instruct
    temperature: 0.0
    max_tokens: 1024
    optimizable_params:
      - temperature
      - top_p
      - max_tokens
      - model_name
    search_space:
      model_name:
        values:
          - meta/llama-3.1-405b-instruct
          - meta/llama-3.1-70b-instruct

  prompt_optimizer:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.5
    max_tokens: 2048


workflow:
  _type: react_agent
  tool_names:
    - email_phishing_analyzer
  llm_name: prompt_optimizer
  verbose: true
  parse_agent_response_max_retries: 3

eval:
  general:
    output_dir: ./.tmp/eval/examples/evaluation_and_profiling/email_phishing_analyzer/original
    verbose: true
    dataset:
        _type: csv
        file_path: examples/evaluation_and_profiling/email_phishing_analyzer/data/smaller_test.csv
        id_key: "subject"
        structure:
          question_key: body
          answer_key: label

  evaluators:
    rag_accuracy:
      _type: ragas
      metric: AnswerAccuracy
      llm_name: prompt_optimizer
    rag_groundedness:
      _type: ragas
      metric: ResponseGroundedness
      llm_name: prompt_optimizer
    llm_latency:
      _type: avg_llm_latency
    token_efficiency:
      _type: avg_tokens_per_llm_end

optimizer:
  output_path: ./.tmp/examples/evaluation_and_profiling/email_phishing_analyzer/optimizer/
  reps_per_param_set: 1
  eval_metrics:
    rag_accuracy:
      evaluator_name: rag_accuracy
      direction: maximize
    rag_groundedness:
      evaluator_name: rag_groundedness
      direction: maximize
    token_efficiency:
      evaluator_name: token_efficiency
      direction: minimize
    latency:
      evaluator_name: llm_latency
      direction: minimize


  numeric:
    enabled: true
    n_trials: 3

  prompt:
    enabled: true
    prompt_population_init_function: prompt_init
    prompt_recombination_function: prompt_recombination
    ga_generations: 3
    ga_population_size: 3
    ga_diversity_lambda: 0.3
    ga_parallel_evaluations: 1

