# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example: Zep with Custom Search Parameters
# This demonstrates how to configure backend-specific search behavior

general:
  telemetry:
    enabled: false
  logging:
    level: DEBUG

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.7
    max_tokens: 1024

memory:
  zep_memory:
    _type: nat.plugins.zep_cloud/zep_memory

functions:
  calculator:
    _type: calculator_multiply

  my_rewoo_agent:
    _type: rewoo_agent
    llm_name: nim_llm
    tool_names: [calculator]
    use_openai_api: true  # REQUIRED for auto_memory_agent
    verbose: true

workflow:
  _type: auto_memory_agent
  inner_agent_name: my_rewoo_agent
  memory_name: zep_memory
  llm_name: nim_llm
  verbose: true

  # Customize Zep search behavior with backend-specific parameters
  search_params:
    mode: "advanced"       # Use Zep's advanced search (slower but more accurate)
    top_k: 10              # Return up to 10 context items
    # search_scope: "both" # Search messages and summaries (if supported)
