# ============================================================================
# Confluence Search Tool
# ============================================================================

functions:
  confluence_search:
    _type: confluence_client
    description: "Searches Confluence content and returns relevant documentation with links"
    base_url: "${CONFLUENCE_BASE_URL}"         # Set environment variable for Confluence URL
    api_token: "${CONFLUENCE_API_TOKEN}"       # Set environment variable for Bearer token
    max_results: 10
    timeout: 30
    # Optional: space_keys: ["TEAM", "DOCS", "PROJECT"]  # Limit search to specific spaces

  current_time:
    _type: current_datetime
    description: "Gets current date and time"

# ----------------------------------------------------------------------------
# LLMS SECTION  
# ----------------------------------------------------------------------------
llms:
  search_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.1
    max_tokens: 4000
    description: "Main LLM for Confluence search and content analysis"

# ----------------------------------------------------------------------------
# WORKFLOW SECTION
# ----------------------------------------------------------------------------
workflow:
  _type: react_agent

  # List tools the agent can use
  tool_names:
    - confluence_search
    - current_time

  # Which LLM to use for reasoning
  llm_name: search_llm

  # Agent behavior settings
  verbose: true
  retry_parsing_errors: true
  max_retries: 3
  max_iterations: 15

  # Custom system prompt for Confluence search and documentation retrieval
  system_message: |
    You are a Confluence Documentation Assistant. Your job is to help users find relevant information from Confluence documentation.

    CRITICAL REQUIREMENTS - YOU MUST FOLLOW ALL:
    1. Search Confluence for relevant content based on user queries
    2. Provide comprehensive answers with links to source documentation
    3. Summarize key information from multiple sources when relevant
    4. Always include direct links to the Confluence pages used
    5. Be thorough but concise in your responses
    6. If no relevant information is found, suggest alternative search terms

    SEARCH STRATEGY:
    - Use search_confluence for general content searches
    - Use search_confluence_by_title for finding specific documentation
    - Use get_confluence_page to get full details of important pages
    - Combine multiple search results for comprehensive answers

    RESPONSE FORMAT:

    **Answer:**
    [Provide a clear, comprehensive answer to the user's question]

    **Sources:**
    - [Page Title](URL) - Brief description of relevance
    - [Page Title](URL) - Brief description of relevance

    **Summary:**
    [Brief summary of key findings and recommendations]

    TOOLS AVAILABLE:
    - confluence_search: Search Confluence content (use search_confluence, search_confluence_by_title, or get_confluence_page)
    - current_time: Get timestamp

    Remember: {tools}
    Available tool names: {tool_names}
