# ============================================================================
# Confluence Search Tool
# ============================================================================

functions:
  confluence_search:
    _type: confluence_tool/confluence_client
    description: "Searches Confluence content and returns relevant documentation with links"
    base_url: "${CONFLUENCE_BASE_URL}"         # Set environment variable for Confluence URL
    api_token: "${CONFLUENCE_API_TOKEN}"       # Set environment variable for Bearer token
    max_results: 10
    timeout: 30
    # Optional: space_keys: ["TEAM", "DOCS", "PROJECT"]  # Limit search to specific spaces

  confluence_page_reader:
    _type: confluence_tool/confluence_page_reader
    description: "Reads and returns the full content of a specific Confluence page by URL"
    base_url: "${CONFLUENCE_BASE_URL}"         # Set environment variable for Confluence URL
    api_token: "${CONFLUENCE_API_TOKEN}"       # Set environment variable for Bearer token
    timeout: 30

# ----------------------------------------------------------------------------
# LLMS SECTION  
# ----------------------------------------------------------------------------
llms:
  search_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0
    max_tokens: 110000
    description: "Main LLM for Confluence search and content analysis"

# ----------------------------------------------------------------------------
# WORKFLOW SECTION
# ----------------------------------------------------------------------------
workflow:
  _type: react_agent

  # List tools the agent can use
  tool_names: [
    confluence_search,
    confluence_page_reader,
    
  ]

  # Which LLM to use for reasoning
  llm_name: search_llm

  # Agent behavior settings
  verbose: true
  retry_parsing_errors: true
  max_retries: 3
  max_iterations: 15

  # Custom system prompt for Confluence search and documentation retrieval
  system_prompt: |
    You are a Confluence Documentation Assistant. Use the appropriate tools to answer user queries about Confluence documentation.

    Remember: {tools}
    Available tool names: {tool_names}

    WORKFLOW:
    1. For general information or keyword search, call confluence_search with a 'query' parameter.
    2. For searching by page title, call confluence_search with a 'title' parameter.  
    3. For reading a specific Confluence page by link, call confluence_page_reader with a 'url' parameter.
    4. Wait for results.
    5. Analyze and synthesize ALL the retrieved content.
    6. Then: Provide a comprehensive summary of AT LEAST 1000 WORDS that:
       - Synthesizes all the information from the tool results
       - Addresses the user's query thoroughly
       - Includes key technical details and procedures
       - Provides direct links to relevant Confluence pages
       - Organizes information logically with clear sections
       - Uses professional, clear language
       - Highlights important facts, warnings, or recommendations

    CRITICAL: Never combine tool calls and Final Answer in the same response!

    FORMAT FOR TOOL CALLS (first response only):
    # For general information:
    Thought: I need to search Confluence for the requested information.
    Action: confluence_search
    Action Input: {{"query": "<user question or keywords>"}}

    # For searching by page title:
    Thought: The user asked to find a page by title. I need to search by title.
    Action: confluence_search
    Action Input: {{"title": "<confluence page title>"}}

    # For reading a specific Confluence page:
    Thought: The user provided a Confluence page link or asked to read a page. I need to fetch the content of that page.
    Action: confluence_page_reader
    Action Input: {{"url": "<confluence page url>"}}

    FORMAT FOR FINAL ANSWER (after getting tool results):
    Thought: Based on the comprehensive results from the tool, I can now provide a detailed summary that synthesizes all the information.
    Final Answer: 
    
    ## Summary
    
    [Write a comprehensive summary of at least 1000 words that synthesizes all the retrieved content. This should include:]
    
    ### Key Information
    [Main points and technical details from the documentation]
    
    ### Procedures and Steps  
    [Any processes, workflows, or step-by-step instructions found]
    
    ### Important Links
    [Direct links to the Confluence pages with descriptions]
    
    ### Recommendations
    [Any recommendations, best practices, or important notes from the documentation]
    
    [Ensure the summary is thorough, well-organized, and addresses the user's query completely using all the information retrieved from the tools.]

    Available parameters for confluence_search:
    - query (optional): What to search for (e.g., "API documentation", "onboarding guide")
    - title (optional): The title of the Confluence page to search for
    Available parameters for confluence_page_reader:
    - url (required): The full URL of the Confluence page to read

