# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Docs: https://docs.coderabbit.ai/getting-started/configure-coderabbit/
language: "en-US"
reviews:
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true # WIP: set false later
    auto_incremental_review: false
  suggested_labels: true
  labeling_instructions:
    - label: "! - Release"
      instructions: >-
        You should only apply this label when the source branch has a name matching the regex pattern `release/\d+\.\d+`
        and the target branch is `main`.
    - label: breaking
      instructions: >-
        Apply this label when the PR introduces changes that break backward compatibility, modify existing APIs in
        incompatible ways, creates a behavioral change, or require users to update their code when upgrading. If you
        apply this label, do not apply the "non-breaking" label.
    - label: bug
      instructions: >-
        Apply this label when the PR fixes a defect, error, or unexpected behavior in the existing codebase. If you
        apply this label do not apply the "doc", "feature request", or "improvement" labels.
    - label: DO NOT MERGE
      instructions: >-
        Apply this label to PRs that should not be merged due to critical issues, incomplete work, or other blocking
        concerns. Check the PR description for specific details about why it should not be merged. There is no need to
        apply this label to draft PRs.
    - label: doc
      instructions: >-
        Apply this label when the PR primarily adds, updates, or improves documentation including README files. If you
        apply this label do not apply the "bug", "feature request", or "improvement" labels.
    - label: duplicate
      instructions: >-
        Apply this label when the PR addresses the same issue or implements the same feature as another existing
        PR or issue.
    - label: external
      instructions: >-
        Apply this label when the PR was submitted by someone who is not a member of the @NVIDIA/agentiq-developers
        GitHub team.
    - label: feature request
      instructions: >-
        Apply this label when the PR implements new functionality, adds new features, or introduces new capabilities
        to the toolkit. If you apply this label do not apply the "bug", "doc", or "improvement" labels.
    - label: improvement
      instructions: >-
        Apply this label when the PR enhances existing functionality without adding completely new features, such as
        performance optimizations, code refactoring, or usability enhancements. If you apply this label do not apply
        the "bug", "doc", or "feature request" labels.
    - label: invalid
      instructions: >-
        Apply this label when the PR contains invalid changes, doesn't follow project guidelines, or has fundamental
        issues that make it unsuitable for the project.
    - label: non-breaking
      instructions: >-
        Apply this label when the PR introduces changes that maintain backward compatibility, does not create a
        behavioral change, and does not require users to modify their existing code. If you apply this label, do not
        apply the "breaking" label.

  suggested_reviewers: false
  tools:
    ruff:
      enabled: true
