# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


general:
  use_uvloop: true

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.0
    max_tokens: 4096

functions:
  calculator_multiply:
    _type: calculator_multiply
    description: "Multiply two numbers"
  calculator_inequality:
    _type: calculator_inequality
    description: "Compare two numbers"
  calculator_divide:
    _type: calculator_divide
    description: "Divide two numbers"
  calculator_subtract:
    _type: calculator_subtract
    description: "Subtract two numbers"

workflow:
  _type: router_agent
  branches: [calculator_multiply, calculator_inequality, calculator_divide, calculator_subtract]
  llm_name: nim_llm
  verbose: true
  routing_request: "Which tool should be used to answer the question?"

# eval:
#   general:
#     output_dir: .tmp/nat/examples/rewoo_agent/
#     dataset:
#       _type: json
#       file_path: examples/agents/data/rewoo.json
#   evaluators:
#     rag_accuracy:
#       _type: ragas
#       metric: AnswerAccuracy
#       llm_name: nim_llm
#     rag_groundedness:
#       _type: ragas
#       metric: ContextRelevance
#       llm_name: nim_llm
#     rag_relevance:
#       _type: ragas
#       metric: ResponseGroundedness
#       llm_name: nim_llm
