[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]


[tool.setuptools.packages.find]
where = ["src"]
include = ["nat.*"]


[tool.setuptools_scm]
git_describe_command = "git describe --long --first-parent"
root = "../.."


[project]
name = "nvidia-nat-strands"
dynamic = ["version"]
dependencies = [
  "nvidia-nat~=1.3",
  "strands-agents==1.12.0",
  "strands-agents-tools==0.2.11",
]
requires-python = ">=3.11,<3.14"
description = "Subpackage for AWS Strands integration in NeMo Agent toolkit"
readme = "src/nat/meta/pypi.md"
keywords = ["ai", "rag", "agents"]
classifiers = ["Programming Language :: Python"]


[tool.uv]
config-settings = { editable_mode = "compat" }


[tool.uv.sources]
nvidia-nat = { workspace = true }


[project.entry-points.'nat.components']
nat_strands = "nat.plugins.strands.register"
