services:
  redis:
    image: redis:8.0
    volumes:
      - redis-data:/data
    container_name: redis
    ports:
      - 6379:6379
    # command: redis-server --save 60 1 --loglevel warning
    # restart: unless-stopped

  # to connect to the above redis server, use host.docker.internal for host
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    restart: unless-stopped

volumes:
  redis-data:
  redisinsight: