# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  use_uvloop: true
  front_end:
    _type: console
    cors:
      allow_origins: ["*"]
  telemetry:
    logging:
      console:
        _type: console
        level: debug

functions:
  weather_update_tool:
    _type: nat_adk_demo/weather_update
    description: "Get the current weather for a specified city"
  get_city_time_tool:
    _type: nat_adk_demo/get_city_time_tool
    transport: "http"
    mcp_tool_name: get_city_time
    url: "http://localhost:9901/mcp"

llms:
  llm:
    _type: litellm
    model: gpt-5
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_API_BASE:-https://api.openai.com/v1}

workflow:
  _type: adk
  name: adk_demo
  llm: llm
  tool_names: [weather_update_tool, get_city_time_tool]
  description: "To get the current weather and time in a specific city"
  prompt: "You are a helpful agent who can answer user questions about weather in a city. You also have a sub-agent that can answer questions about the time in a city."
