# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  front_end:
    _type: console
    cors:
      allow_origins: ["*"]
  telemetry:
    logging:
      console:
        _type: console
        level: debug
    tracing:
      otelcollector:
        _type: otelcollector
        endpoint: ${OTEL_ENDPOINT:-http://localhost:6006/v1/traces}
        project: nat_autogen_demo

llms:
  openai_llm:
    _type: openai
    model_name: ${OPENAI_MODEL_NAME:-gpt-5}
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_API_BASE}

functions:
  weather_update_tool:
    _type: nat_autogen_demo/weather_update_autogen
    description: "Get the current weather for a specified city"

workflow:
  _type: autogen_team
  llm_name: openai_llm
  description: "To get the current weather and time in a specific city"
  tool_names: [weather_update_tool]
  query_processing_agent_name: WeatherAndTimeAgent
  query_processing_agent_instructions: |
    You are an agent that provides the current weather and time information.
    When asked about the weather, provide the current weather conditions.
    When asked about the time, provide the current local time.
    If asked about anything else, respond with 'I can only provide weather and time information.'
    Once you are done, reply with the text 'DONE'.
  final_response_agent_name: FinalResponseAgent
  final_response_agent_instructions: |
    You are the final response agent.
    Your role is to provide a concise and clear answer based on the information provided by other agents.
    Once you are done, reply with the final answer and then say 'APPROVE'.
