general:
  use_uvloop: true


functions:
  rag_tool:
    _type: rag_library_mode
    base_url: "http://localhost:19530"
    vdb_top_k: 10
    reranker_top_k: 100
    collection_names: ["cuda_docs"]
    topic: Retrieve relevant documents from the database relevant to the query


llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0
    max_tokens: 4096
    top_p: 1


workflow:
  _type: tool_calling_agent
  tool_names:
   - rag_tool
  verbose: true
  llm_name: nim_llm
