llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.1
  nim_small_llm:
    _type: nim
    model_name: meta/llama3-8b-instruct
    temperature: 0.1

workflow:
  _type: rl_with_openpipe_art
  larger_model: nim_llm
  smaller_model: nim_small_llm
  max_parser_retries: 3
  play_larger_random: true

eval:
  general:
    max_concurrency: 8
    output_dir: .tmp/nat/examples/rl_openpipe/eval
    dataset:
      _type: json
      file_path: examples/finetuning/rl_with_openpipe_art/data/data.json

  evaluators:
    rl_accuracy:
      _type: rl_accuracy