llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.1

  openpipe_llm:
    _type: openai
    # Model name should be the same as the trainer adapter config base_model
    model_name: Qwen/Qwen2.5-7B-Instruct
    base_url: http://localhost:8000/v1
    api_key: default
    temperature: 1.0

workflow:
  _type: rl_with_openpipe_art
  larger_model: nim_llm
  smaller_model: openpipe_llm
  max_parser_retries: 3
  play_larger_random: true

eval:
  general:
    max_concurrency: 32
    output_dir: .tmp/nat/examples/rl_openpipe/eval/finetune
    dataset:
      _type: json
      file_path: examples/finetuning/rl_with_openpipe_art/data/data.json

  evaluators:
    rl_accuracy:
      _type: rl_accuracy

#################################
#### Begin Finetuning Config ####
#################################

trajectory_builders:
  openpipe_traj_builder:
    _type: openpipe_art_traj_builder
    num_generations: 1

trainer_adapters:
  openpipe_trainer_adapter:
    _type: openpipe_art_trainer_adapter
    backend:

      # General Backend Arguments
      ip: "0.0.0.0"
      port: 7623
      name: "tic_tac_toe"
      project: "tic_tac_toe_project"
      base_model: "Qwen/Qwen2.5-7B-Instruct"
      api_key: "default"

      # Model Initialization Arguments
      init_args:
        max_seq_length: 8192

      # VLLM Engine Arguments
      engine_args:
        gpu_memory_utilization: 0.9
        tensor_parallel_size: 1

    # Training Arguments
    # Adjust these arguments based on GPU size
    training:
      learning_rate: 1e-5

trainers:
  openpipe_trainer:
    _type: openpipe_art_trainer

######### Put it all together into a finetuning config

finetuning:
  enabled: true
  trainer: openpipe_trainer
  trajectory_builder: openpipe_traj_builder
  trainer_adapter: openpipe_trainer_adapter
  reward_function:
    name: rl_accuracy
  num_epochs: 50
  output_dir: ./.tmp/nat/finetuning/tic_tac_toe


