llms:
  small_llm:
    _type: openai
    model_name: Qwen/Qwen2.5-3B-Instruct
    base_url: http://localhost:8000/v1
    temperature: 0.1

workflow:
  _type: rl_with_openpipe_art
  player_model: small_llm
  max_parser_retries: 2

eval:
  general:
    max_concurrency: 16
    output_dir: .tmp/nat/examples/rl_openpipe/eval/pre_train
    dataset:
      _type: json
      file_path: examples/finetuning/rl_with_openpipe_art/data/eval_data.json

  evaluators:
    percent_games_won:
      _type: percent_games_won