# ============================================================================
# Friday AI Assistant Configuration
# Combining Confluence Documentation Search and Loki Log Analysis
# ============================================================================

# Functions section - Define both Confluence and Loki tools
functions:
  
  # Confluence search functionality
  confluence_search:
    _type: friday/confluence_client
    description: "Searches Confluence content and returns relevant documentation with links"
    base_url: "${CONFLUENCE_BASE_URL}"         # Set environment variable for Confluence URL
    api_token: "${CONFLUENCE_API_TOKEN}"       # Set environment variable for Bearer token
    max_results: 10
    timeout: 30
    # Optional: space_keys: ["TEAM", "DOCS", "PROJECT"]  # Limit search to specific spaces

  # Confluence page reader functionality
  confluence_page_reader:
    _type: friday/confluence_page_reader
    description: "Reads and returns the full content of a specific Confluence page by URL"
    base_url: "${CONFLUENCE_BASE_URL}"         # Set environment variable for Confluence URL
    api_token: "${CONFLUENCE_API_TOKEN}"       # Set environment variable for Bearer token
    timeout: 30

  # Loki log analysis functionality
  log_analyzer:
    _type: friday/loki_log_analyzer
    description: "Analyze logs from Loki using natural language queries with error detection and pattern recognition"
    
    # Loki connection settings - Use Grafana proxy with correct UID format
    # Available datasources (choose one):
    # - loki-us-east-1: ee0goqc2a64u8b
    # - loki-us-west-2: ce1n6e6v256v4c  
    # - loki-eu-north-1: fe1n6e6m54o3ka
    # - loki-ap-northeast-1: ee1n6e6vtm2o0c
    loki_url: "https://dashboards.telemetry.dgxc.ngc.nvidia.com/api/datasources/proxy/uid/ee0goqc2a64u8b"
    timeout: 30
    
    # Query settings
    default_time_range: "1h"           # Default search window: 1h, 30m, 24h, 7d
    max_log_lines: 1000                # Maximum log entries to retrieve
    
    # Authentication for Loki API access
    # Option 1: API Token (recommended - uses LOKI_API_TOKEN environment variable)
    api_token: "${LOKI_API_TOKEN}"
    
    # Alternative authentication options (uncomment if needed):
    # Option 2: Basic Authentication
    # auth_username: "your_loki_username"
    # auth_password: "your_loki_password"
    
    # Option 3: Bearer Token
    # bearer_token: "${LOKI_BEARER_TOKEN}"

  # Utility function for timestamps
  current_time:
    _type: current_datetime
    description: "Gets current date and time for analysis context"

# ----------------------------------------------------------------------------
# LLMS SECTION  
# ----------------------------------------------------------------------------
llms:
  friday_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.1
    max_tokens: 4000
    description: "Main LLM for Friday AI Assistant - handles both documentation search and log analysis"

# ----------------------------------------------------------------------------
# WORKFLOW SECTION
# ----------------------------------------------------------------------------
workflow:
  _type: react_agent

  # List tools the agent can use
  tool_names:
    - confluence_search
    - confluence_page_reader
    - log_analyzer
    - current_time

  # Which LLM to use for reasoning
  llm_name: friday_llm

  # Agent behavior settings
  verbose: true
  retry_parsing_errors: true
  max_retries: 3
  max_iterations: 15

  # Custom system prompt for Friday AI Assistant
  system_prompt: |
    You are Friday, an AI Assistant that combines documentation search and log analysis capabilities. You help users find information from Confluence documentation and analyze logs from Loki systems.

    Remember: {tools}
    Available tool names: {tool_names}

    WORKFLOW:
    1. For general information or keyword search, call confluence_search with a 'query' parameter.
    2. For searching by page title, call confluence_search with a 'title' parameter.
    3. For reading a specific Confluence page by link, call confluence_page_reader with a 'url' parameter.
    4. For log analysis, call log_analyzer with a 'query' parameter.
    5. Wait for results.
    6. Then: Provide Final Answer based on those results, including links and summaries.

    CRITICAL: Never combine tool calls and Final Answer in the same response!

    FORMAT FOR TOOL CALLS (first response only):
    # For general information:
    Thought: I need to search Confluence for the requested information.
    Action: confluence_search
    Action Input: {{"query": "<user question or keywords>"}}

    # For searching by page title:
    Thought: The user asked to find a page by title. I need to search by title.
    Action: confluence_search
    Action Input: {{"title": "<confluence page title>"}}

    # For reading a specific Confluence page:
    Thought: The user provided a Confluence page link or asked to read a page. I need to fetch the content of that page.
    Action: confluence_page_reader
    Action Input: {{"url": "<confluence page url>"}}

    # For log analysis:
    Thought: I need to query the logs for the requested information.
    Action: log_analyzer
    Action Input: {{"query": "<keyword>", "cluster": "<cluster_name>", "time_range": "<time_range>"}}


    FORMAT FOR FINAL ANSWER (after getting tool results):
    Thought: Based on the results, I can now provide a summary.
    Final Answer: [Comprehensive answer with direct links to Confluence pages, summaries, and recommendations]

    Available parameters for confluence_search:
    - query (optional): What to search for (e.g., "API documentation", "onboarding guide")
    - title (optional): The title of the Confluence page to search for
    Available parameters for confluence_page_reader:
    - url (required): The full URL of the Confluence page to read
    Available parameters for log_analyzer:
    - query (required): What to search for (e.g., "error", "warning", "*")
    - time_range (optional): "30m", "1h", "2h", "24h", etc.
    - cluster (optional): "gcp-cbf-cs-002", "kratos-multitenant"
    - hostname (optional): "a4xl-007", "cpu-small-001"  
    - log_level (optional): "error", "warn", "info"

    TOOL USAGE STRATEGIES:

    **Confluence Search (confluence_search):**
    - Use search_confluence for general content searches
    - Use search_confluence with query parameter for keyword searches
    - Combine multiple search results for comprehensive answers

    **Confluence Page Reader (confluence_page_reader):**
    - Use read_page to get full content of specific Confluence pages by URL
    - Use when you have a direct Confluence page URL to read complete content
    - Ideal for getting detailed information from specific documentation pages

    **Log Analysis (log_analyzer):**
    - Use analyze_logs with natural language queries
    - Apply appropriate filters: cluster, hostname, log_level, time_range
    - Focus on error detection and pattern recognition
    - Provide actionable insights and recommendations 