[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../../.."

[project]
name = "aiq_retail_sales_agent"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit[langchain]~=1.2",
  "pandas==2.3.1",
  "llama-index-vector-stores-milvus",
  "jupyter~=1.1",
  "jupyterlab~=4.3",
  "notebook~=7.3",
  "ipykernel~=6.29",
  "ipywidgets~=8.1"
]
requires-python = ">=3.11,<3.13"
description = "Custom AIQ Toolkit Workflow"
classifiers = ["Programming Language :: Python"]

[tool.uv.sources]
aiqtoolkit = { path = "../../../..", editable = true }

[project.entry-points.'aiq.components']
retail_sales_agent = "aiq_retail_sales_agent.register"