[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../.."

[project]
name = "nat_authenticated_requests"
dynamic = ["version"]
dependencies = [
  "nvidia-nat",
  "nvidia-nat[langchain]",
  "httpx",
]
requires-python = ">=3.11,<3.13"
description = "Custom NeMo Agent toolkit workflow demonstrating making authenticated requests"
classifiers = ["Programming Language :: Python"]

[tool.uv.sources]
nvidia-nat = { path = "../../..", editable = true }

[project.entry-points.'nat.components']
authenticated_requests = "authenticated_requests.register"
