# Quick 10-second load test configuration

config_file: "examples/getting_started/simple_calculator/configs/config.yml"

server:
  host: "localhost"
  port: 9901
  transport: "streamable-http"

load_test:
  num_concurrent_users: 5
  duration_seconds: 10
  warmup_seconds: 2

output:
  directory: "load_test_results"

tool_calls:
  - tool_name: "calculator_multiply"
    args:
      text: "2 * 3"

  - tool_name: "calculator_divide"
    args:
      text: "10 / 2"
