[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../.."

[project]
name = "retail_sales_agent"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit[langchain]",
  "llama-index-vector-stores-milvus"
]
requires-python = ">=3.11,<3.13"
description = "Custom AIQ Toolkit Workflow"
classifiers = ["Programming Language :: Python"]

[tool.uv.sources]
aiqtoolkit = { path = "../../..", editable = true }

[project.entry-points.'aiq.components']
retail_sales_agent = "retail_sales_agent.register"