general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: WARN

functions:
  auth_tool:
    _type: auth_tool
    auth_provider: test_auth_provider

  ip_info_tool:
    _type: ip_lookup
    authentication_function: auth_tool

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0
    max_tokens: 1024

authentication:
  test_auth_provider:
    _type: oauth2_authorization_code
    client_server_host: "localhost"
    client_server_port: 8000
    authorization_url: http://127.0.0.1:5000/oauth/authorize
    token_url: http://127.0.0.1:5000/oauth/token
    token_endpoint_auth_method: client_secret_post
    scope:
      - openid
      - profile
      - email
    client_id: zHahts9MDgHLZ1vXv9iJ9lqH
    client_secret: vPGkGDgUmE0PsmN9R3zOUI8rXQu44v71FQmJ8Ucf4KnbdZCg

workflow:
  _type: react_agent
  tool_names:
    - ip_info_tool
  llm_name: nim_llm
  verbose: true
  parse_agent_response_max_retries: 3