# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0


functions:
  knowledge_base:
    _type: url_directory
    urls:
      strands_agent_loop: "https://strandsagents.com/latest/documentation/docs/user-guide/concepts/agents/agent-loop/"
      strands_prompts: "https://strandsagents.com/latest/documentation/docs/user-guide/concepts/agents/prompts/"
    description: "Get vetted URLs for Strands documentation about agent loops and prompts. Use this to find the right URL, then use http_request to fetch the content."
  current_datetime:
    _type: current_datetime

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-405b-instruct
    temperature: 0.0
    max_tokens: 4000
  bedrock_llm:
    _type: aws_bedrock
    model_name: anthropic.claude-3-5-sonnet-20240620-v1:0
    region_name: us-east-1
    max_tokens: 4000
  openai_llm:
    _type: openai
    model_name: gpt-4o-mini
    temperature: 0.0

workflow:
  _type: strands_demo
  llm_name: nim_llm
  tool_names: [knowledge_base, current_datetime]
  system_prompt: "You are a helpful assistant. All answers must be sourced from the curated knowledge base via your available tools. Find the information first, then respond succinctly."

eval:
  general:
    output:
      dir: ./.tmp/nat/examples/frameworks/strands_demo/eval/
      cleanup: true
    dataset:
      _type: json
      file_path: examples/frameworks/strands_demo/data/strands.json
